### ISSUE TITLE
Running server.py results in exceptions.Auth0Error

### ISSUE THREAD

**Issue by gerardoprada** [auth0-samples/auth0-python-web-app#18]
Steps to reproduce problem:
 
1. Download sample project from Auth0 client (`.env` is already populated with correct client ID, domain, and secret).
2. Add `callback url` to settings in Auth0 client.
3. Create virtualenv and run `pip install -r requirements.txt`.
4. Run `python3 server.py` and navigate to http://localhost:3000/
5. Press `SIGNIN` button.

**ERROR GET RESPONSE**
`http://localhost:3000/callback?error=access_denied&error_description=Service%20not%20found%3A%20%7BAPI_AUDIENCE%7D`

**ERROR**
`auth0.v3.exceptions.Auth0Error: invalid_request: Missing required parameter: code`

**TRACEBACK:**
```
Traceback (most recent call last):
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/Documents/auth0/00-starter-seed/server.py", line 64, in callback_handling
    AUTH0_CLIENT_SECRET, code, AUTH0_CALLBACK_URL)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/auth0/v3/authentication/get_token.py", line 49, in authorization_code
    headers={'Content-Type': 'application/json'}
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/auth0/v3/authentication/base.py", line 11, in post
    return self._process_response(response)
  File "/home/developer/.virtualenvs/auth0-starter-seed/lib/python3.5/site-packages/auth0/v3/authentication/base.py", line 22, in _process_response
    message=text['error_description'])
auth0.v3.exceptions.Auth0Error: invalid_request: Missing required parameter: code
```

**Comment by Annyv2** [comment]
Hi! You need to fill in the Audience in the `.env` file to avoid [this error](http://localhost:3000/callback?error=access_denied&error_description=Service%20not%20found%3A%20%7BAPI_AUDIENCE%7D) https://github.com/auth0-samples/auth0-python-web-app/blob/master/00-Starter-Seed/.env.example#L5. If you are not implementing any API you can use `https://YOUR_DOMAIN.auth0.com/userinfo` as the audience
